volumes:
  postgres:
    external: true
  redis:
    external: true

services:
  fiber-note:
    build: .
    environment:
      PASSWORD: ${PASSWORD}
      DATABASE_URL: postgres://fibernote:fibernote@postgres/fibernote
      REDIS_URL: redis://redis:6379/1
      RAILS_SERVE_STATIC_FILES: true
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 -S --spider 127.0.0.1:3000/_health || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_interval: 5s


  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: fibernote
      POSTGRES_USER: fibernote
      POSTGRES_DB: fibernote
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fibernote -d fibernote" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_interval: 5s
    
  redis:
    image: bitnami/redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/bitnami/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_interval: 5s
